### ISSUE TITLE
 missing the core4inet_ttescheduler.h

### ISSUE THREAD

**Issue by tixiangking** [CoRE-RG/CoRE4INET#7]
Hi CoRE-RG group,

I have been working with your AS6802 example. I have observed an issue:
When I run the program, it prompts me for missing the core4inet_ttescheduler.h, which I can not find in the GitHub repository.

Maybe  I'm doing some wrong

**Comment by THaeckel** [comment]
Hello tyxiangking,
The AS6802 synchronization protocol is currently not functional. The other AS6802 examples should work fine.

Best regards,
Timo

**Comment by Musteblume** [comment]
Hello tyxiangking,
the current nightly version does not contain the state machines for the AS6802 synchronization due to major API changes of the Scheduler module. If you would like to simulate AS6802 synchronization in detail you must use [this Version](http://core4inet.core-rg.de/files/other/TTE4INET_src_20130515_nightly.tar.gz) with OMNeT++ 4.4.1 and INET Framework 2.1.0. The version is from may 2013 and does not contain the new features introduced afterwards. Due to a name collision with the IN enum, this Version does not build on Windows systems.

Best regards,
Philipp

**Comment by liranaa** [comment]
When I used the newer version CoRE4INET to do simulation experiments on end-to-end time delay of TTEthernet, I had the problem of core4INet_TTescheduler.h file missing. In newer versions, is the time synchronization between terminal nodes and switches already completed automatically, or do I need to do some configuration?Or do I have to use a lower version of CoRE4INET to do this part work?

**Comment by Musteblume** [comment]
Hi, in the current version of CoRE4INET the default sync module is called "DummySync". This module synchronises all devices without a sync protocol implementation the forwards messages in the network. But, the clocks in the devices behave like there is a sync protocol active. DummySync can also be configured with a precision in seconds.
